# Generated by Django 4.2.3 on 2023-07-22 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(auto_now=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('ml', 'male'), ('fm', 'female')], default='ml', max_length=2)),
                ('phone', models.IntegerField()),
                ('mailid', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ('name',),
            },
        ),
    ]
