# Generated by Django 4.2.3 on 2023-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='course',
            new_name='purpose',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=None),
        ),
    ]
