# Generated by Django 4.2.3 on 2023-07-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('cs', 'Computer sceince'), ('cm', 'Commerce'), ('ms', 'Medical sceince')], max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purpose',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('purchase', 'Purchase'), ('return', 'Return')], max_length=250),
        ),
    ]
