# Generated by Django 4.2.3 on 2023-07-25 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_profile_department_alter_profile_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=False, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(10)]),
        ),
    ]
