# Generated by Django 4.2.3 on 2023-07-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user_id',
        ),
    ]
