# Generated by Django 4.2.3 on 2023-07-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
